import type { Metadata } from "next";
import { Slackey, Averia_Sans_Libre } from "next/font/google";
import "./globals.css";
import Image from "next/image";

const slackey = Slackey({
  subsets: ["latin"],
  weight: "400",
})

const averiaSansLibre = Averia_Sans_Libre({
  subsets: ["latin"],
  weight: ["400", "700"]
});

export const metadata: Metadata = {
  title: "Nook Book",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const header = (
    <nav className='bg-white w-full mx-auto py-4'>
      <div className="flex items-center mx-8 md:mx-16">
        <Image
          src="https://dodo.ac/np/images/8/85/Menu_Island_Life_101_NH_Icon.png"
          alt="Nook Book"
          width={45}
          height={45}
        />
        <span className={`${slackey.className} text-orange-400 dark:text-teal-500 px-2 text-2xl`}>
          Nook Book
        </span>
      </div>
    </nav>
  )

  const footer = (
    <footer className='bg-white w-full mx-auto py-4 text-center text-orange-400 dark:text-teal-500'>
      <p>Fanmade with love 🧡 © Federico Ramírez 2025</p>
    </footer>
  )

  return (
    <html lang="en">
      <body
        className={`${averiaSansLibre.className} w-full max-w-full min-h-screen bg-orange-300 dark:bg-teal-400`}
      >
        {header}
        {children}
        {footer}
      </body>
    </html>
  );
}
